<?php

namespace Database\Seeders;

use VoyagerBread\Traits\BreadSeeder;
use Illuminate\Database\Seeder;

class ManageUsersBreadTableSeeder extends Seeder
{
    use BreadSeeder;

    public function bread()
    {
        return [
            // usually the name of the table
            'name'                  => 'manage_users',
            'slug'                  => 'manage-users',
            'display_name_singular' => 'Manage User',
            'display_name_plural'   => 'Manage Users',
            'icon'                  => 'voyager-group',
            'model_name'            => 'App\Models\ManageUser',
            'controller'            => '',
            'generate_permissions'  => 1,
            'description'           => '',
            'details'               => null
        ];
    }

    public function inputFields()
    {
        return [
            'id' => [
                'type'         => 'number',
                'display_name' => 'ID',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => new \stdClass,
                'order'        => 1,
            ],
            'mobile' => [
                'type'         => 'text',
                'display_name' => 'mobile',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => new \stdClass,
                'order'        => 2,
            ],
            'user_id' => [
                'type'         => 'number',
                'display_name' => 'user_id',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => new \stdClass,
                'order'        => 3,
            ],
            'parent' => [
                'type'         => 'number',
                'display_name' => 'parent',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => new \stdClass,
                'order'        => 4,
            ],
            'address' => [
                'type'         => 'text',
                'display_name' => 'address',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => new \stdClass,
                'order'        => 5,
            ],
            'billing_name' => [
                'type'         => 'text',
                'display_name' => 'billing_name',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => new \stdClass,
                'order'        => 6,
            ],
            'billing_address' => [
                'type'         => 'text',
                'display_name' => 'billing_address',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 7,
            ],
            'billing_city' => [
                'type'         => 'text',
                'display_name' => 'billing_city',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 8,
            ],
            'billing_zip' => [
                'type'         => 'text',
                'display_name' => 'billing_zip',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 9,
            ],
            'billing_state' => [
                'type'         => 'text',
                'display_name' => 'billing_state',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => new \stdClass,
                'order'        => 10,
            ],
            'billing_country' => [
                'type'         => 'text',
                'display_name' => 'billing_country',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => new \stdClass,
                'order'        => 11,
            ],
            'billing_gst' => [
                'type'         => 'number',
                'display_name' => 'billing_gst',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => new \stdClass,
                'order'        => 12,
            ],
            'status' => [
                'type'         => 'select_dropdown',
                'display_name' => 'status',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '{"default":"Active","options":{"Active":"Active","Expired":"Expired","Deleted":"Deleted"}}',
                'order'        => 13,
            ],
            'expires_at' => [
                'type'         => 'timestamp',
                'display_name' => 'expires_at',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => new \stdClass,
                'order'        => 14,
            ],
            'created_at' => [
                'type'         => 'timestamp',
                'display_name' => 'created_at',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => new \stdClass,
                'order'        => 15,
            ],
            'updated_at' => [
                'type'         => 'timestamp',
                'display_name' => 'updated_at',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => new \stdClass,
                'order'        => 16,
            ],
            'manage_user_belongsto_user_relationship' => [
                'type'         => 'relationship',
                'display_name' => 'users',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '{"model":"App\\Models\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"name","pivot_table":"users","pivot":"0","taggable":null}',
                'order'        => 17,
            ],
            // 'deleted_at' => [
            //     'type'         => 'timestamp',
            //     'display_name' => 'Deleted At',
            //     'required'     => 0,
            //     'browse'       => 0,
            //     'read'         => 0,
            //     'edit'         => 0,
            //     'add'          => 0,
            //     'delete'       => 0,
            //     'details'      => new \stdClass,
            //     'order'        => 13,
            // ],
        ];
    }

    public function menuEntry()
    {
        return [
            'role'        => 'admin',
            'title'       => 'Manage Users',
            'url'         => '',
            'route'       => 'voyager.manage-users.index',
            'target'      => '_self',
            'icon_class'  => 'voyager-group',
            'color'       => null,
            'parent_id'   => null,
            'parameters' => null,
            'order'       => 13,

        ];
    }
}
